### ISSUE TITLE
Blind kenrel estimation

### ISSUE THREAD

**Issue by YuqiangY** [shadyabh/Correction-Filter#10]
Thanks for your attractive work！
I have a problem with the method used in blind kernel estimation. I notice you define four tensors and convolve them to get an unknown kernel, do you ever attempt to use a linear network e.g., KernelGAN, to replace this method? What is the difference between them?
Looking forward to your reply, thanks.

**Comment by shadyabh** [comment]
Thank you for your interest.

We tried this approach previously, we used convolution instead of FFT. There is no problem with using linear network, but for computing the correction filter you will need to find the equivalent filter using FFT anyway, so why not use FFT, it is more efficient.

Note that the code runs on the latest version of pyTorch that supports complex tensors (previously complex tensor was defined as dimension expansion).

Good luck

**Comment by YuqiangY** [comment]
> Thank you for your interest.
> 
> We tried this approach previously, we used convolution instead of FFT. There is no problem with using linear network, but for computing the correction filter you will need to find the equivalent filter using FFT anyway, so why not use FFT, it is more efficient.
> 
> Note that the code runs on the latest version of pyTorch that supports complex tensors (previously complex tensor was defined as dimension expansion).
> 
> Good luck

Thanks for your reply!
