### ISSUE TITLE
Test Question

### ISSUE THREAD

**Issue by rainyfly** [shadyabh/Correction-Filter#11]
Thanks for your work. I just wonder why I handle the data for myself, for example, convolution with blur sigma=1.1 and kernel width=32, then direct downsampling, the PSNR results are bad. But when use your code, 'fft_down' to handle the image, the results are good. And I found the kernel width must be even, if it is odd the results are still bad using your code.

**Comment by shadyabh** [comment]
Thanks for your interest.

When down-sampling an image (or signal in general) you need to maintain the same view, i.e. you do not want the down-sampled image to be shifted w.r.t. the original image.

The down-sampling model is defined as applying a filter followed by direct sub-sampling (i.e. sampling the image directly at 0, alpha, 2*alpha...). Therefore one would need to consider this when building the down-sampling kernel.

For example, when the scale factor is 2, you need to sample the analytic continuous kernel at [..., -2.5, -0.5, 0.5, 2.5, ...], when the scale factor is 4 you sample it with the grid [..., -4.5, -0.5, 0.5, 4.5, ...]. This is because the output grid and the input grid do not align when the scale factor is even. But when for example the scale factor is odd, e.g. 3, then you sample the analytic kernel at [..., -3, 0, 3, ...].

If your down-sampling code doesn't behave similarly then you will not be considering the measurement model assumed by this work.

By the way, many apply blur on the image then down-sample it with bicubic (imresize), note that this is not right, here you apply explicitly a blur filter, and implicitly apply another bicubic kernel. In order for this to work the sampling kernel given to the correction filter needs to be modified.

I hope I made it clear.
Good luck.

**Comment by rainyfly** [comment]
Thank you very much. I got it.
