### ISSUE TITLE
Kernel size and for non-blind setting

### ISSUE THREAD

**Issue by jfun9494** [shadyabh/Correction-Filter#3]
I want to give my own kernels for the non-blind setting. I see that in correct_imgs.py the kernel is Gaussian with size 32 for scale 2. Is there any restriction for the kernel size (minimum size, odd or even)? Should the kernel be centralized?

**Comment by shadyabh** [comment]
If the scale factor is even then the size of the sampling kernel needs to be even, and all kernels needs to be centralized for both even and odd scale factors, otherwise you will get shifts in the corrected image. In the case of Gaussian kernel with even scale factor for example, the peak of the Gaussian is not sampled, i.e. (0,0) is not included in the sampling grid.

**Comment by FuzhiYang** [comment]
Hi, Nice work! 
I tested "correct_img.py" on Set5 dataset. I blured the image with 14x14 gaussian blur kernel with sigma 1.3, and then I used matlab's bicubic imresize function to x2 downsample it. When I ran "correct_img.py", I changed the "sigma" from 2.5/np.sqrt(2) to 1.3, "s_size" from 32 to 14. I ran the code, but the results seem strange. 

hr image
![baby](https://user-images.githubusercontent.com/11538235/90517149-98e9ec80-e197-11ea-80eb-5279ed9ba492.png)

14x14 gaussian blur kernel with sigma 1.3, and x2 bicubic downsample
![baby](https://user-images.githubusercontent.com/11538235/90517282-c3d44080-e197-11ea-8e7d-4be040952762.png)

results:
![baby_x2_corr_corrected](https://user-images.githubusercontent.com/11538235/90517320-d0f12f80-e197-11ea-81e7-47a3a794dca3.png)

Did I miss something important in your code? Could you help me?

**Comment by shadyabh** [comment]
Hi, 

You can solve this in two ways:
1) leave the s_size set to 32.
2) If you have to use this size you will need to change line 11 in correction_func.py to
q = q_unscaled[:,:,0::2,0::2]

The reason this occurred is that the size of correction filter is derived from the size of the sampling kernel, and because we perform decimation in line 11, depends on where you start the decimation, you can get wrong results, the same as you got.

**Comment by FuzhiYang** [comment]
Thank you for your advice. It helps a lot! I've got a normal SR result.

When I evaluated PSNR on Set14 dataset. I blured the image with 32x32 gaussian blur kernel with sigma 2.5/sqrt(2), like below:
![comic](https://user-images.githubusercontent.com/11538235/90646658-09f9d480-e26a-11ea-87d8-ca5a5219bd33.png)

Then I ran "correct_imgs.py" to get the corrected results like this:
![comic_x2_corr_corrected](https://user-images.githubusercontent.com/11538235/90646715-1847f080-e26a-11ea-89ee-3ee36c10534d.png)

Finally I forward this corrected image to RCAN_x2 model and got this:
![comic_x2_corr_corrected](https://user-images.githubusercontent.com/11538235/90646836-3b72a000-e26a-11ea-8574-9deced7594af.png)

But the PSNR on Set14 is only about 24, which is far lower than the reported number in the paper, 31.272. Did I make some mistakes during these steps? Could you share the details of your degradation process? (gaussian blur, bicubic downsample, etc)
